export type WireSpan = {
  offset: string;
  hex: string;
  field: string;
  description: string;
  section: "header" | "question" | "answer" | "additional";
};

export const exampleWireSpans: WireSpan[] = [
  {
    offset: "0000",
    hex: "85 ea",
    field: "ID (Transaction ID)",
    description: "0x85ea generated with crypto/rand to prevent off-path answer forgery.",
    section: "header",
  },
  {
    offset: "0002",
    hex: "84 00",
    field: "Flags",
    description: "QR=1 (Response), Opcode=0 (QUERY), AA=1 (Authoritative), TC=0, RD=0, RA=0, RCODE=0 (NOERROR).",
    section: "header",
  },
  {
    offset: "0004",
    hex: "00 01",
    field: "QDCOUNT",
    description: "1 Question entry in the Question section.",
    section: "header",
  },
  {
    offset: "0006",
    hex: "00 02",
    field: "ANCOUNT",
    description: "2 Resource Records in the Answer section.",
    section: "header",
  },
  {
    offset: "0008",
    hex: "00 00",
    field: "NSCOUNT",
    description: "0 Authority records.",
    section: "header",
  },
  {
    offset: "000a",
    hex: "00 01",
    field: "ARCOUNT",
    description: "1 Additional record (EDNS0 OPT pseudo-record).",
    section: "header",
  },
  {
    offset: "000c",
    hex: "07 65 78 61 6d 70 6c 65 03 63 6f 6d 00",
    field: "QNAME",
    description: 'example.com. encoded as labels [7] "example" [3] "com" [0] (null root byte).',
    section: "question",
  },
  {
    offset: "0019",
    hex: "00 01",
    field: "QTYPE",
    description: "Type A (Host IPv4 address).",
    section: "question",
  },
  {
    offset: "001b",
    hex: "00 01",
    field: "QCLASS",
    description: "Class IN (Internet).",
    section: "question",
  },
  {
    offset: "001d",
    hex: "c0 0c",
    field: "NAME (Compression Pointer)",
    description: "RFC 1035 pointer 0xc00c: top 2 bits set (11), pointing to offset 0x000c (example.com.).",
    section: "answer",
  },
  {
    offset: "001f",
    hex: "00 01",
    field: "TYPE",
    description: "Type A (1).",
    section: "answer",
  },
  {
    offset: "0021",
    hex: "00 01",
    field: "CLASS",
    description: "Class IN (1).",
    section: "answer",
  },
  {
    offset: "0023",
    hex: "00 00 01 2c",
    field: "TTL",
    description: "300 seconds time-to-live.",
    section: "answer",
  },
  {
    offset: "0027",
    hex: "00 04",
    field: "RDLENGTH",
    description: "4 octets for IPv4 address payload.",
    section: "answer",
  },
  {
    offset: "0029",
    hex: "ac 42 93 f3",
    field: "RDATA",
    description: "IPv4 address 172.66.147.243.",
    section: "answer",
  },
  {
    offset: "002d",
    hex: "c0 0c",
    field: "NAME (Compression Pointer)",
    description: "Pointer to 0x000c (example.com.).",
    section: "answer",
  },
  {
    offset: "002f",
    hex: "00 01",
    field: "TYPE",
    description: "Type A (1).",
    section: "answer",
  },
  {
    offset: "0031",
    hex: "00 01",
    field: "CLASS",
    description: "Class IN (1).",
    section: "answer",
  },
  {
    offset: "0033",
    hex: "00 00 01 2c",
    field: "TTL",
    description: "300 seconds time-to-live.",
    section: "answer",
  },
  {
    offset: "0037",
    hex: "00 04",
    field: "RDLENGTH",
    description: "4 octets.",
    section: "answer",
  },
  {
    offset: "0039",
    hex: "68 14 17 9a",
    field: "RDATA",
    description: "IPv4 address 104.20.23.154.",
    section: "answer",
  },
  {
    offset: "003d",
    hex: "00",
    field: "NAME",
    description: "Root domain (.) for OPT pseudo-record.",
    section: "additional",
  },
  {
    offset: "003e",
    hex: "00 29",
    field: "TYPE",
    description: "Type OPT (41) RFC 6891 EDNS0.",
    section: "additional",
  },
  {
    offset: "0040",
    hex: "04 d0",
    field: "UDP Payload Size",
    description: "1232 octets advertised maximum payload size.",
    section: "additional",
  },
  {
    offset: "0042",
    hex: "00 00 00 00",
    field: "Extended RCODE & Flags",
    description: "Version 0, DO=0 (DNSSEC OK bit decoded).",
    section: "additional",
  },
  {
    offset: "0046",
    hex: "00 00",
    field: "RDLENGTH",
    description: "0 options.",
    section: "additional",
  },
];
